name: actionlint

on:
  pull_request:
    paths: ['.github/**']

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: rhysd/actionlint@main

  next-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: .github/actions/next-version/test.sh
