on:
  workflow_call:
    inputs:
      environment:
        required: false
        type: string
      repo:
        required: true
        type: string
      repo-prefix:
        required: true
        type: string

jobs:
  Build-deploy-ecr-images:
    name: 'Build/Deploy ECR images'
    runs-on: ubuntu-latest
    needs: Deploy-infra
    environment: ${{ inputs.environment }}
    # if: ${{ (github.event.pull_request.merged == true || github.event_name == 'push') && needs.pre-check.outputs.should_skip != 'true' }}
        
    steps:
    - name: Checkout
      uses: actions/checkout@v2
        
    - name: Download doppler
      uses: dopplerhq/cli-action@v2

    - name: Download doppler secrets to .env file
      run: |
        doppler -p chat-stat -c dev secrets download --no-file --format env > .env
      env:
        DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}
          
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_DEPLOYER_ROLE }}
        aws-region: ${{secrets.AWS_DEFAULT_REGION}}
        role-duration-seconds: 1200
            
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
            
    - name: Create Unique image tag
      id: vars
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT 
          
    - name: Build and push
      uses: docker/build-push-action@v4
      env:
        ECR_REGISTRY: ${{steps.login-ecr.outputs.registry}}
        SHA: ${{steps.vars.outputs.sha_short}}
      with:
        context: .
        push: true
        build-args: |
          TWITCH_CLIENT_ID=${{secrets.TWITCH_CLIENT_ID}}
          TWITCH_CLIENT_SECRETS=${{secrets.TWITCH_CLIENT_SECRETS}}
        tags: |
          ${{env.ECR_REGISTRY}}/${{inputs.repo-prefix}}-${{inputs.repo}}:latest
          ${{env.ECR_REGISTRY}}/${{inputs.repo-prefix}}-${{inputs.repo}}:${{env.SHA}}

