on:
  workflow_call:
    inputs:
      artifacts_dir:
        required: dir
        type: string
          
      lambda_src:
        required: true
        type: string
          
      lambda_output:
        required: true
        type: string
      
      go-version:
        required: false
        type: string
        default: "1.21.4"
          
jobs:
  Build-Lambda:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
        
    - name: Set up Go
      uses: actions/setup-go@v4

    - name: Build Binary
      run: |
        env GOOS=linux GOARCH=arm64 go build \
        -o ${{inputs.lambda_output}} \
        ${{inputs.lambda_src}}

    - name: Upload Artifacts
      id: cache
      uses: actions/upload-artifact@v3
      with:
        name: lambdas
        path: ${{ inputs.artifacts_dir }}
          
    # - name: Test
    #   run: go test -v ./...

