jobs:
  Build-Lambdas:
    needs: pre-check
    if: ${{ (github.event.pull_request.merged == true || github.event_name == 'push') && needs.pre-check.outputs.should_skip != 'true' }}
    runs-on: ubuntu-latest
      
    strategy:
      fail-fast: true
      matrix:
        include:
          - src: lambda/hello/main.go
            output: lambda/bin/lambda_hello.exe
          - src: lambda/twitch/webhookCallback/main.go
            output: lambda/bin/lambda_webhook.exe
          
    steps:
    - name: Checkout
      uses: actions/checkout@v2
        
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build Executables
      run: go build -o ${{ env.INFRA_DIR }}/${{matrix.output}} src/cmd/${{matrix.src}}

    - name: Upload Artifacts
      id: cache
      uses: actions/upload-artifact@v3
      with:
        name: lambdas
        path: ${{ env.INFRA_DIR }}/lambda/bin/

