on:
  workflow_call:
    inputs:
      artifacts_dir:
        required: true
        type: string
          
      lambda_dir:
        required: true
        type: string
          
      lambda_output:
        required: true
        type: string
          
      rust_version:
        required: false
        type: string
        default: stable
          
      cache_file:
        required: false
        type: string
        default: Cargo.toml
          
      src-filters:
        description: JSON object of files or directories that will conditionally determine if running docker build is necessary
        required: false
        type: string
        default: |
          lambda: 'infra/modules/aws/lambda/**'
          
jobs:
  Changes:
    runs-on: ubuntu-24.04-arm
    permissions:
      pull-requests: read
    outputs:
      lambda: ${{ steps.filter.outputs.lambda }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
        
    - uses: dorny/paths-filter@v3
      id: filter
      with: 
        base: ${{ github.ref }}
        filters: ${{ inputs.src-filters }}
          
  Test-Rust-Lambdas:
    needs: Changes
    if: ${{ needs.changes.outputs.lambda == 'true' }}
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ inputs.rust_version }}
          profile: minimal
          override: true

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: ${{ inputs.lambda_dir }}
          key: ${{ format('cargo-cache-{0}', hashFiles(format('{0}/{1}', inputs.lambda_dir, inputs.cache_file))) }}
         
      - name: Run Tests
        run: |
          cargo test \
          --manifest-path ${{ inputs.lambda_dir }}/Cargo.toml \
          
  Build-Rust-Lambdas:
    needs: Changes
    if: ${{ needs.changes.outputs.lambda == 'true' }}
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ inputs.rust_version }}
          profile: minimal
          override: true

      # - name: Install Zig toolchain
      #   uses: korandoru/setup-zig@v1
      #   with:
      #     zig-version: 0.13.0

      - name: Install Cargo Lambda
        uses: jaxxstorm/action-install-gh-release@v1.9.0
        with:
          repo: cargo-lambda/cargo-lambda
          platform: linux
          arch: aarch64
         
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: ${{ inputs.lambda_dir }}
          key: ${{ format('cargo-cache-{0}', hashFiles(format('{0}/{1}', inputs.lambda_dir, inputs.cache_file))) }}

      - name: Build Lambdas
        run: |
          cargo lambda build \
          --arm64 \
          --compiler cargo \
          --release \
          --output-format zip \
          --manifest-path ${{ inputs.lambda_dir }}/Cargo.toml \
          --lambda-dir ${{ inputs.lambda_output }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: lambdas
          path: ${{ inputs.artifacts_dir }}
